// Centralised mock dataset. Replace with FastAPI responses later.
import site1 from "@/assets/site-1.jpg";
import site2 from "@/assets/site-2.jpg";
import site3 from "@/assets/site-3.jpg";
import site4 from "@/assets/site-4.jpg";
import site5 from "@/assets/site-5.jpg";
import site6 from "@/assets/site-6.jpg";
import site7 from "@/assets/site-7.jpg";

import type {
  Activity,
  Drawing,
  DocumentPage,
  Folder,
  Photo,
  Project,
  ProjectFile,
  ProjectMember,
  TrashedFile,
  User,
} from "./types";

export const currentUser: User = {
  id: "u-1",
  name: "Milind Awasarmol",
  role: "Owner",
  email: "milind@maa-consultant.com",
  initials: "MA",
};

export const organisation = {
  name: "Milind Awasarmol & Associates",
  gstin: "27AAECA1234K1ZP",
  office: "Andheri East, Mumbai 400069",
  phone: "+91 22 4890 2210",
};

export const users: User[] = [
  currentUser,
  {
    id: "u-3",
    name: "Sneha Kulkarni",
    role: "Architect",
    email: "sneha@maa-consultant.com",
    initials: "SK",
  },
  {
    id: "u-4",
    name: "Rohit Deshmukh",
    role: "Structural Consultant",
    email: "rohit@rdconsultants.in",
    initials: "RD",
  },
  {
    id: "u-5",
    name: "Pratibha Nair",
    role: "Project Manager",
    email: "pratibha@maa-consultant.com",
    initials: "PN",
  },
  {
    id: "u-6",
    name: "Imran Shaikh",
    role: "MEP Coordinator",
    email: "imran@maa-consultant.com",
    initials: "IS",
  },
];

export const projects: Project[] = [
  {
    id: "aaditya-residency",
    name: "Aaditya Residency",
    code: "ACL-2601",
    location: "Ghatkopar West, Mumbai",
    client: "Residential",
    category: "Residential — G+12",
    status: "Active",
    fileCount: 148,
    updatedAt: "2026-09-26T11:20:00+05:30",
    startedOn: "2025-11-04",
    manager: "Pratibha Nair",
    briefing:
      "G+12 residential tower on a 1,450 sq.m plot. Raft foundation completed; podium and typical floor slabs in progress. Structural drawings are at revision R03 following the September consultant review.",
  },
  {
    id: "commercial-office-interior",
    name: "Commercial Office Interior",
    code: "ACL-2604",
    location: "Bandra Kurla Complex, Mumbai",
    client: "Commercial",
    category: "Interior Fit-out — 18,000 sq.ft",
    status: "On Hold",
    fileCount: 62,
    updatedAt: "2026-09-19T17:05:00+05:30",
    startedOn: "2026-03-18",
    manager: "Sneha Kulkarni",
    briefing:
      "Interior fit-out across two floors. Work paused pending client approval on the revised MEP services layout and false ceiling coordination.",
  },
  {
    id: "shirdi-plaza",
    name: "Shirdi Plaza Retail Block",
    code: "ACL-2598",
    location: "Shirdi, Ahmednagar",
    client: "Retail",
    category: "Retail — G+2",
    status: "Active",
    fileCount: 97,
    updatedAt: "2026-09-25T09:40:00+05:30",
    startedOn: "2025-08-12",
    manager: "Milind Awasarmol",
    briefing:
      "G+2 retail block with basement parking. Blockwork and plaster in progress on the ground level; electrical layout revised to R03 to accommodate the additional signage load.",
  },
  {
    id: "nashik-warehouse",
    name: "Nashik Warehouse Shed",
    code: "ACL-2571",
    location: "Satpur MIDC, Nashik",
    client: "Industrial",
    category: "PEB Warehouse — 42,000 sq.ft",
    status: "Completed",
    fileCount: 71,
    updatedAt: "2026-06-30T16:10:00+05:30",
    startedOn: "2024-09-02",
    manager: "Milind Awasarmol",
    briefing:
      "Pre-engineered warehouse shed handed over in June 2026. As-built drawings and completion certificates archived.",
  },
];

const folderNames = [
  "Structural",
  "Architectural",
  "Electrical",
  "Plumbing",
  "MEP",
  "Reports",
  "Contracts",
  "Specifications",
  "Other",
];

export const folders: Folder[] = projects.flatMap((project) => [
  {
    id: `${project.id}-root`,
    projectId: project.id,
    name: "Documents",
    parentId: null,
    fileCount: 0,
  },
  ...folderNames.map((name, index) => ({
    id: `${project.id}-${name.toLowerCase()}`,
    projectId: project.id,
    name,
    parentId: `${project.id}-root`,
    fileCount: [9, 7, 5, 3, 4, 6, 2, 3, 2][index] ?? 2,
  })),
]);

const kb = 1024;

export const files: ProjectFile[] = [
  {
    id: "f-1",
    projectId: "aaditya-residency",
    folderId: "aaditya-residency-structural",
    name: "STR-104-R03.pdf",
    kind: "PDF",
    revision: "R03",
    sizeBytes: 3820 * kb,
    modifiedAt: "2026-09-26T11:20:00+05:30",
    status: "Ready",
    metadata: {
      uploadedBy: "Milind Awasarmol",
      uploadedAt: "2026-09-26T11:20:00+05:30",
      discipline: "STRUCTURAL",
      source: "Consultant issue",
      pages: 8,
    },
  },
  {
    id: "f-2",
    projectId: "aaditya-residency",
    folderId: "aaditya-residency-structural",
    name: "STR-104-R02.pdf",
    kind: "PDF",
    revision: "R02",
    sizeBytes: 3640 * kb,
    modifiedAt: "2026-08-30T10:02:00+05:30",
    status: "Superseded",
    metadata: {
      uploadedBy: "Milind Awasarmol",
      uploadedAt: "2026-08-30T10:02:00+05:30",
      discipline: "STRUCTURAL",
      source: "Consultant issue",
      pages: 8,
    },
  },
  {
    id: "f-3",
    projectId: "aaditya-residency",
    folderId: "aaditya-residency-structural",
    name: "STR-104-R01.pdf",
    kind: "PDF",
    revision: "R01",
    sizeBytes: 3510 * kb,
    modifiedAt: "2026-07-14T15:48:00+05:30",
    status: "Superseded",
    metadata: {
      uploadedBy: "Rohit Deshmukh",
      uploadedAt: "2026-07-14T15:48:00+05:30",
      discipline: "STRUCTURAL",
      source: "Consultant issue",
      pages: 7,
    },
  },
  {
    id: "f-4",
    projectId: "aaditya-residency",
    folderId: "aaditya-residency-structural",
    name: "Raft-Foundation-Reinforcement-Schedule.xlsx",
    kind: "XLSX",
    revision: "R02",
    sizeBytes: 412 * kb,
    modifiedAt: "2026-09-21T12:30:00+05:30",
    status: "Ready",
    metadata: {
      uploadedBy: "Rohit Deshmukh",
      uploadedAt: "2026-09-21T12:30:00+05:30",
      discipline: "STRUCTURAL",
      source: "Email attachment",
    },
  },
  {
    id: "f-5",
    projectId: "aaditya-residency",
    folderId: "aaditya-residency-architectural",
    name: "A-204-Ground-Floor-Plan-R02.pdf",
    kind: "PDF",
    revision: "R02",
    sizeBytes: 2980 * kb,
    modifiedAt: "2026-09-24T18:15:00+05:30",
    status: "Ready",
    metadata: {
      uploadedBy: "Sneha Kulkarni",
      uploadedAt: "2026-09-24T18:15:00+05:30",
      discipline: "ARCHITECTURAL",
      source: "Site upload",
      pages: 4,
    },
  },
  {
    id: "f-6",
    projectId: "aaditya-residency",
    folderId: "aaditya-residency-architectural",
    name: "A-301-Typical-Floor-Plan-R01.dwg",
    kind: "DWG",
    revision: "R01",
    sizeBytes: 7140 * kb,
    modifiedAt: "2026-09-12T09:55:00+05:30",
    status: "Ready",
    metadata: {
      uploadedBy: "Sneha Kulkarni",
      uploadedAt: "2026-09-12T09:55:00+05:30",
      discipline: "ARCHITECTURAL",
      source: "Site upload",
    },
  },
  {
    id: "f-7",
    projectId: "aaditya-residency",
    folderId: "aaditya-residency-electrical",
    name: "Electrical-Layout-R03.pdf",
    kind: "PDF",
    revision: "R03",
    sizeBytes: 2210 * kb,
    modifiedAt: "2026-09-25T14:05:00+05:30",
    status: "Processing",
    metadata: {
      uploadedBy: "Imran Shaikh",
      uploadedAt: "2026-09-25T14:05:00+05:30",
      discipline: "ELECTRICAL",
      source: "Consultant issue",
      pages: 6,
    },
  },
  {
    id: "f-8",
    projectId: "aaditya-residency",
    folderId: "aaditya-residency-mep",
    name: "MEP-201-R01.pdf",
    kind: "PDF",
    revision: "R01",
    sizeBytes: 4420 * kb,
    modifiedAt: "2026-09-18T11:12:00+05:30",
    status: "Ready",
    metadata: {
      uploadedBy: "Imran Shaikh",
      uploadedAt: "2026-09-18T11:12:00+05:30",
      discipline: "MEP",
      source: "Consultant issue",
      pages: 12,
    },
  },
  {
    id: "f-9",
    projectId: "aaditya-residency",
    folderId: "aaditya-residency-plumbing",
    name: "PL-108-Water-Supply-Riser-R01.pdf",
    kind: "PDF",
    revision: "R01",
    sizeBytes: 1680 * kb,
    modifiedAt: "2026-09-08T16:40:00+05:30",
    status: "Ready",
    metadata: {
      uploadedBy: "Imran Shaikh",
      uploadedAt: "2026-09-08T16:40:00+05:30",
      discipline: "PLUMBING",
      source: "Consultant issue",
      pages: 3,
    },
  },
  {
    id: "f-10",
    projectId: "aaditya-residency",
    folderId: "aaditya-residency-reports",
    name: "Cube-Test-Report-M30-Sep-2026.pdf",
    kind: "PDF",
    revision: "R01",
    sizeBytes: 640 * kb,
    modifiedAt: "2026-09-23T10:20:00+05:30",
    status: "Ready",
    metadata: {
      uploadedBy: "Milind Awasarmol",
      uploadedAt: "2026-09-23T10:20:00+05:30",
      discipline: "STRUCTURAL",
      source: "Lab report",
      pages: 2,
    },
  },
  {
    id: "f-11",
    projectId: "aaditya-residency",
    folderId: "aaditya-residency-reports",
    name: "Soil-Investigation-Report.pdf",
    kind: "PDF",
    revision: "R01",
    sizeBytes: 5120 * kb,
    modifiedAt: "2026-01-19T13:00:00+05:30",
    status: "Ready",
    metadata: {
      uploadedBy: "Rohit Deshmukh",
      uploadedAt: "2026-01-19T13:00:00+05:30",
      discipline: "STRUCTURAL",
      source: "Consultant issue",
      pages: 24,
    },
  },
  {
    id: "f-12",
    projectId: "aaditya-residency",
    folderId: "aaditya-residency-contracts",
    name: "Work-Order-Blockwork-Contractor.pdf",
    kind: "PDF",
    revision: "R01",
    sizeBytes: 320 * kb,
    modifiedAt: "2026-08-02T11:30:00+05:30",
    status: "Ready",
    metadata: {
      uploadedBy: "Pratibha Nair",
      uploadedAt: "2026-08-02T11:30:00+05:30",
      discipline: "GENERAL",
      source: "Office upload",
      pages: 6,
    },
  },
  {
    id: "f-13",
    projectId: "aaditya-residency",
    folderId: "aaditya-residency-specifications",
    name: "Concrete-Mix-Specification-M30.docx",
    kind: "DOCX",
    revision: "R02",
    sizeBytes: 148 * kb,
    modifiedAt: "2026-05-27T09:10:00+05:30",
    status: "Ready",
    metadata: {
      uploadedBy: "Rohit Deshmukh",
      uploadedAt: "2026-05-27T09:10:00+05:30",
      discipline: "STRUCTURAL",
      source: "Office upload",
    },
  },
  {
    id: "f-14",
    projectId: "aaditya-residency",
    folderId: "aaditya-residency-other",
    name: "Site-Photographs-14-Sep-2026.zip",
    kind: "ZIP",
    revision: "R01",
    sizeBytes: 86400 * kb,
    modifiedAt: "2026-09-14T19:25:00+05:30",
    status: "Failed",
    metadata: {
      uploadedBy: "Milind Awasarmol",
      uploadedAt: "2026-09-14T19:25:00+05:30",
      discipline: "GENERAL",
      source: "Site upload",
    },
  },
  {
    id: "f-15",
    projectId: "commercial-office-interior",
    folderId: "commercial-office-interior-mep",
    name: "MEP-Services-Coordination-R02.pdf",
    kind: "PDF",
    revision: "R02",
    sizeBytes: 3980 * kb,
    modifiedAt: "2026-09-19T17:05:00+05:30",
    status: "Ready",
    metadata: {
      uploadedBy: "Imran Shaikh",
      uploadedAt: "2026-09-19T17:05:00+05:30",
      discipline: "MEP",
      source: "Consultant issue",
      pages: 9,
    },
  },
  {
    id: "f-16",
    projectId: "commercial-office-interior",
    folderId: "commercial-office-interior-architectural",
    name: "INT-112-False-Ceiling-Layout-R01.pdf",
    kind: "PDF",
    revision: "R01",
    sizeBytes: 2410 * kb,
    modifiedAt: "2026-09-11T12:45:00+05:30",
    status: "Ready",
    metadata: {
      uploadedBy: "Sneha Kulkarni",
      uploadedAt: "2026-09-11T12:45:00+05:30",
      discipline: "ARCHITECTURAL",
      source: "Office upload",
      pages: 5,
    },
  },
  {
    id: "f-17",
    projectId: "shirdi-plaza",
    folderId: "shirdi-plaza-electrical",
    name: "Electrical-Layout-R03.pdf",
    kind: "PDF",
    revision: "R03",
    sizeBytes: 2680 * kb,
    modifiedAt: "2026-09-25T09:40:00+05:30",
    status: "Ready",
    metadata: {
      uploadedBy: "Imran Shaikh",
      uploadedAt: "2026-09-25T09:40:00+05:30",
      discipline: "ELECTRICAL",
      source: "Consultant issue",
      pages: 7,
    },
  },
  {
    id: "f-18",
    projectId: "shirdi-plaza",
    folderId: "shirdi-plaza-structural",
    name: "STR-212-Column-Layout-R02.pdf",
    kind: "PDF",
    revision: "R02",
    sizeBytes: 3120 * kb,
    modifiedAt: "2026-09-16T15:20:00+05:30",
    status: "Ready",
    metadata: {
      uploadedBy: "Rohit Deshmukh",
      uploadedAt: "2026-09-16T15:20:00+05:30",
      discipline: "STRUCTURAL",
      source: "Consultant issue",
      pages: 6,
    },
  },
  {
    id: "f-19",
    projectId: "nashik-warehouse",
    folderId: "nashik-warehouse-reports",
    name: "As-Built-Completion-Report.pdf",
    kind: "PDF",
    revision: "R01",
    sizeBytes: 7420 * kb,
    modifiedAt: "2026-06-30T16:10:00+05:30",
    status: "Ready",
    metadata: {
      uploadedBy: "Milind Awasarmol",
      uploadedAt: "2026-06-30T16:10:00+05:30",
      discipline: "GENERAL",
      source: "Office upload",
      pages: 32,
    },
  },
];

export const drawings: Drawing[] = [
  {
    id: "d-1",
    projectId: "aaditya-residency",
    number: "STR-104",
    name: "Podium Slab Reinforcement Detail",
    discipline: "STRUCTURAL",
    revision: "R03",
    status: "Current",
    date: "2026-09-26",
    fileName: "STR-104-R03.pdf",
  },
  {
    id: "d-2",
    projectId: "aaditya-residency",
    number: "STR-104",
    name: "Podium Slab Reinforcement Detail",
    discipline: "STRUCTURAL",
    revision: "R02",
    status: "Superseded",
    date: "2026-08-30",
    fileName: "STR-104-R02.pdf",
  },
  {
    id: "d-3",
    projectId: "aaditya-residency",
    number: "A-204",
    name: "Ground Floor Plan",
    discipline: "ARCHITECTURAL",
    revision: "R02",
    status: "Current",
    date: "2026-09-24",
    fileName: "A-204-Ground-Floor-Plan-R02.pdf",
  },
  {
    id: "d-4",
    projectId: "aaditya-residency",
    number: "A-301",
    name: "Typical Floor Plan — Level 3 to 12",
    discipline: "ARCHITECTURAL",
    revision: "R01",
    status: "Current",
    date: "2026-09-12",
    fileName: "A-301-Typical-Floor-Plan-R01.dwg",
  },
  {
    id: "d-5",
    projectId: "aaditya-residency",
    number: "ELE-118",
    name: "Riser and Distribution Layout",
    discipline: "ELECTRICAL",
    revision: "R03",
    status: "For Review",
    date: "2026-09-25",
    fileName: "Electrical-Layout-R03.pdf",
  },
  {
    id: "d-6",
    projectId: "aaditya-residency",
    number: "MEP-201",
    name: "Services Coordination — Podium",
    discipline: "MEP",
    revision: "R01",
    status: "Current",
    date: "2026-09-18",
    fileName: "MEP-201-R01.pdf",
  },
  {
    id: "d-7",
    projectId: "aaditya-residency",
    number: "PL-108",
    name: "Water Supply Riser Diagram",
    discipline: "PLUMBING",
    revision: "R01",
    status: "Current",
    date: "2026-09-08",
    fileName: "PL-108-Water-Supply-Riser-R01.pdf",
  },
  {
    id: "d-8",
    projectId: "commercial-office-interior",
    number: "INT-112",
    name: "False Ceiling Layout — Level 8",
    discipline: "ARCHITECTURAL",
    revision: "R01",
    status: "Current",
    date: "2026-09-11",
    fileName: "INT-112-False-Ceiling-Layout-R01.pdf",
  },
  {
    id: "d-9",
    projectId: "commercial-office-interior",
    number: "MEP-308",
    name: "Services Coordination — Level 8 and 9",
    discipline: "MEP",
    revision: "R02",
    status: "For Review",
    date: "2026-09-19",
    fileName: "MEP-Services-Coordination-R02.pdf",
  },
  {
    id: "d-10",
    projectId: "shirdi-plaza",
    number: "STR-212",
    name: "Column Layout — Ground Level",
    discipline: "STRUCTURAL",
    revision: "R02",
    status: "Current",
    date: "2026-09-16",
    fileName: "STR-212-Column-Layout-R02.pdf",
  },
  {
    id: "d-11",
    projectId: "shirdi-plaza",
    number: "ELE-204",
    name: "Signage and Facade Lighting Load",
    discipline: "ELECTRICAL",
    revision: "R03",
    status: "Current",
    date: "2026-09-25",
    fileName: "Electrical-Layout-R03.pdf",
  },
];

export const photos: Photo[] = [
  {
    id: "p-21",
    projectId: "aaditya-residency",
    title: "Podium beam reinforcement",
    visit: "Site Visit — 26 Sep 2026",
    capturedAt: "2026-09-26T12:05:00+05:30",
    url: site5,
    uploadedBy: "Milind Awasarmol",
  },
  {
    id: "p-22",
    projectId: "aaditya-residency",
    title: "Level 5 blockwork start",
    visit: "Site Visit — 26 Sep 2026",
    capturedAt: "2026-09-26T12:30:00+05:30",
    url: site7,
    uploadedBy: "Milind Awasarmol",
  },
  {
    id: "p-23",
    projectId: "aaditya-residency",
    title: "Column casting — grid C4",
    visit: "Site Visit — 26 Sep 2026",
    capturedAt: "2026-09-26T13:10:00+05:30",
    url: site6,
    uploadedBy: "Rohit Deshmukh",
  },
  {
    id: "p-24",
    projectId: "aaditya-residency",
    title: "Tower east elevation",
    visit: "Site Visit — 26 Sep 2026",
    capturedAt: "2026-09-26T13:40:00+05:30",
    url: site2,
    uploadedBy: "Rohit Deshmukh",
  },
  {
    id: "p-25",
    projectId: "aaditya-residency",
    title: "Slab deck cover blocks",
    visit: "Site Visit — 14 Sep 2026",
    capturedAt: "2026-09-14T10:45:00+05:30",
    url: site5,
    uploadedBy: "Pratibha Nair",
  },
  {
    id: "p-26",
    projectId: "aaditya-residency",
    title: "Formwork stripping — Level 3",
    visit: "Site Visit — 14 Sep 2026",
    capturedAt: "2026-09-14T11:15:00+05:30",
    url: site6,
    uploadedBy: "Pratibha Nair",
  },
  {
    id: "p-27",
    projectId: "aaditya-residency",
    title: "Internal blockwork — Level 2",
    visit: "Site Visit — 02 Sep 2026",
    capturedAt: "2026-09-02T16:00:00+05:30",
    url: site7,
    uploadedBy: "Milind Awasarmol",
  },
  {
    id: "p-28",
    projectId: "aaditya-residency",
    title: "Rebar yard stock check",
    visit: "Site Visit — 02 Sep 2026",
    capturedAt: "2026-09-02T16:30:00+05:30",
    url: site5,
    uploadedBy: "Milind Awasarmol",
  },
  {
    id: "p-1",
    projectId: "aaditya-residency",
    title: "Column formwork — Level 4",
    visit: "Site Visit — 26 Sep 2026",
    capturedAt: "2026-09-26T10:40:00+05:30",
    url: site1,
    uploadedBy: "Milind Awasarmol",
  },
  {
    id: "p-2",
    projectId: "aaditya-residency",
    title: "Podium slab concreting",
    visit: "Site Visit — 26 Sep 2026",
    capturedAt: "2026-09-26T11:05:00+05:30",
    url: site4,
    uploadedBy: "Milind Awasarmol",
  },
  {
    id: "p-3",
    projectId: "aaditya-residency",
    title: "Tower elevation — north face",
    visit: "Site Visit — 26 Sep 2026",
    capturedAt: "2026-09-26T11:30:00+05:30",
    url: site6,
    uploadedBy: "Milind Awasarmol",
  },
  {
    id: "p-4",
    projectId: "aaditya-residency",
    title: "Rebar placement inspection",
    visit: "Site Visit — 14 Sep 2026",
    capturedAt: "2026-09-14T09:15:00+05:30",
    url: site5,
    uploadedBy: "Pratibha Nair",
  },
  {
    id: "p-5",
    projectId: "aaditya-residency",
    title: "Slab pour progress — bay 3",
    visit: "Site Visit — 14 Sep 2026",
    capturedAt: "2026-09-14T09:50:00+05:30",
    url: site4,
    uploadedBy: "Pratibha Nair",
  },
  {
    id: "p-6",
    projectId: "aaditya-residency",
    title: "Scaffolding and safety netting",
    visit: "Site Visit — 14 Sep 2026",
    capturedAt: "2026-09-14T10:20:00+05:30",
    url: site2,
    uploadedBy: "Pratibha Nair",
  },
  {
    id: "p-7",
    projectId: "aaditya-residency",
    title: "Formwork stacking area",
    visit: "Site Visit — 02 Sep 2026",
    capturedAt: "2026-09-02T15:10:00+05:30",
    url: site6,
    uploadedBy: "Milind Awasarmol",
  },
  {
    id: "p-8",
    projectId: "aaditya-residency",
    title: "Level 3 slab finishing",
    visit: "Site Visit — 02 Sep 2026",
    capturedAt: "2026-09-02T15:35:00+05:30",
    url: site7,
    uploadedBy: "Milind Awasarmol",
  },
  {
    id: "p-9",
    projectId: "commercial-office-interior",
    title: "Partition framing — Level 8",
    visit: "Site Visit — 19 Sep 2026",
    capturedAt: "2026-09-19T16:20:00+05:30",
    url: site3,
    uploadedBy: "Sneha Kulkarni",
  },
  {
    id: "p-10",
    projectId: "commercial-office-interior",
    title: "Ceiling services routing",
    visit: "Site Visit — 19 Sep 2026",
    capturedAt: "2026-09-19T16:45:00+05:30",
    url: site7,
    uploadedBy: "Sneha Kulkarni",
  },
  {
    id: "p-11",
    projectId: "shirdi-plaza",
    title: "Ground level blockwork",
    visit: "Site Visit — 25 Sep 2026",
    capturedAt: "2026-09-25T09:10:00+05:30",
    url: site1,
    uploadedBy: "Milind Awasarmol",
  },
  {
    id: "p-12",
    projectId: "shirdi-plaza",
    title: "Facade progress",
    visit: "Site Visit — 25 Sep 2026",
    capturedAt: "2026-09-25T09:35:00+05:30",
    url: site2,
    uploadedBy: "Milind Awasarmol",
  },
];

export const members: ProjectMember[] = [
  {
    id: "m-1",
    projectId: "aaditya-residency",
    name: "Pratibha Nair",
    role: "Project Manager",
    email: "pratibha@maa-consultant.com",
    access: "Owner",
    initials: "PN",
  },
  {
    id: "m-2",
    projectId: "aaditya-residency",
    name: "Milind Awasarmol",
    role: "Owner",
    email: "milind@maa-consultant.com",
    access: "Owner",
    initials: "MA",
  },
  {
    id: "m-3",
    projectId: "aaditya-residency",
    name: "Rohit Deshmukh",
    role: "Structural Consultant",
    email: "rohit@rdconsultants.in",
    access: "Viewer",
    initials: "RD",
  },
  {
    id: "m-4",
    projectId: "aaditya-residency",
    name: "Sneha Kulkarni",
    role: "Architect",
    email: "sneha@maa-consultant.com",
    access: "Editor",
    initials: "SK",
  },
  {
    id: "m-5",
    projectId: "commercial-office-interior",
    name: "Sneha Kulkarni",
    role: "Architect",
    email: "sneha@maa-consultant.com",
    access: "Owner",
    initials: "SK",
  },
  {
    id: "m-6",
    projectId: "commercial-office-interior",
    name: "Imran Shaikh",
    role: "MEP Coordinator",
    email: "imran@maa-consultant.com",
    access: "Editor",
    initials: "IS",
  },
  {
    id: "m-8",
    projectId: "shirdi-plaza",
    name: "Milind Awasarmol",
    role: "Owner",
    email: "milind@maa-consultant.com",
    access: "Owner",
    initials: "MA",
  },
  {
    id: "m-9",
    projectId: "nashik-warehouse",
    name: "Milind Awasarmol",
    role: "Owner",
    email: "milind@maa-consultant.com",
    access: "Owner",
    initials: "MA",
  },
];

export const activity: Activity[] = [
  {
    id: "a-1",
    projectId: "aaditya-residency",
    projectName: "Aaditya Residency",
    actor: "Milind Awasarmol",
    action: "uploaded",
    target: "STR-104-R03.pdf",
    at: "2026-09-27T11:20:00+05:30",
    kind: "upload",
  },
  {
    id: "a-2",
    projectId: "aaditya-residency",
    projectName: "Aaditya Residency",
    actor: "Rohit Deshmukh",
    action: "revised structural drawing",
    target: "STR-104 — R02 to R03",
    at: "2026-09-27T10:05:00+05:30",
    kind: "revision",
  },
  {
    id: "a-3",
    projectId: "shirdi-plaza",
    projectName: "Shirdi Plaza Retail Block",
    actor: "Imran Shaikh",
    action: "uploaded",
    target: "Electrical-Layout-R03.pdf",
    at: "2026-09-27T09:40:00+05:30",
    kind: "upload",
  },
  {
    id: "a-4",
    projectId: "aaditya-residency",
    projectName: "Aaditya Residency",
    actor: "Milind Awasarmol",
    action: "uploaded 3 photos to",
    target: "Site Visit — 26 Sep 2026",
    at: "2026-09-26T11:35:00+05:30",
    kind: "photo",
  },
  {
    id: "a-5",
    projectId: "aaditya-residency",
    projectName: "Aaditya Residency",
    actor: "Sneha Kulkarni",
    action: "uploaded",
    target: "A-204-Ground-Floor-Plan-R02.pdf",
    at: "2026-09-26T18:15:00+05:30",
    kind: "upload",
  },
  {
    id: "a-6",
    projectId: "commercial-office-interior",
    projectName: "Commercial Office Interior",
    actor: "Sneha Kulkarni",
    action: "created folder",
    target: "MEP / Coordination",
    at: "2026-09-25T14:50:00+05:30",
    kind: "folder",
  },
  {
    id: "a-7",
    projectId: "aaditya-residency",
    projectName: "Aaditya Residency",
    actor: "Pratibha Nair",
    action: "added",
    target: "Rohit Deshmukh as Viewer",
    at: "2026-09-24T10:15:00+05:30",
    kind: "member",
  },
  {
    id: "a-8",
    projectId: "aaditya-residency",
    projectName: "Aaditya Residency",
    actor: "Milind Awasarmol",
    action: "uploaded",
    target: "Cube-Test-Report-M30-Sep-2026.pdf",
    at: "2026-09-23T10:20:00+05:30",
    kind: "upload",
  },
  {
    id: "a-9",
    projectId: "aaditya-residency",
    projectName: "Aaditya Residency",
    actor: "Pratibha Nair",
    action: "moved to trash",
    target: "STR-103-R01.pdf",
    at: "2026-09-20T17:00:00+05:30",
    kind: "delete",
  },
  {
    id: "a-10",
    projectId: "shirdi-plaza",
    projectName: "Shirdi Plaza Retail Block",
    actor: "Milind Awasarmol",
    action: "created folder",
    target: "Shirdi Plaza Retail Block / Contracts",
    at: "2026-09-18T12:10:00+05:30",
    kind: "folder",
  },
];

export const trashedFiles: TrashedFile[] = [
  {
    id: "t-1",
    folder: "Structural",
    originalLocation: "Aaditya Residency / Structural / Superseded",
    name: "STR-103-R01.pdf",
    projectName: "Aaditya Residency",
    deletedBy: "Pratibha Nair",
    deletedAt: "2026-09-20T17:00:00+05:30",
    sizeBytes: 2180 * kb,
  },
  {
    id: "t-2",
    folder: "Interiors",
    originalLocation: "Commercial Office Interior / Interiors / Layouts",
    name: "INT-110-Flooring-Layout-R01.pdf",
    projectName: "Commercial Office Interior",
    deletedBy: "Sneha Kulkarni",
    deletedAt: "2026-09-12T11:25:00+05:30",
    sizeBytes: 1440 * kb,
  },
  {
    id: "t-3",
    folder: "Survey",
    originalLocation: "Shirdi Plaza Retail Block / Survey / Site",
    name: "Old-Boundary-Survey.dwg",
    projectName: "Shirdi Plaza Retail Block",
    deletedBy: "Milind Awasarmol",
    deletedAt: "2026-08-29T15:40:00+05:30",
    sizeBytes: 5320 * kb,
  },
  {
    id: "t-4",
    folder: "Site Photos",
    originalLocation: "Aaditya Residency / Site Photos / August",
    name: "Podium-Pour-Duplicate-0814.jpg",
    projectName: "Aaditya Residency",
    deletedBy: "Rahul Deshmukh",
    deletedAt: "2026-08-21T09:10:00+05:30",
    sizeBytes: 3900 * kb,
  },
  {
    id: "t-5",
    folder: "Contracts",
    originalLocation: "Shirdi Plaza Retail Block / Contracts / Drafts",
    name: "BOQ-Civil-Draft-v2.xlsx",
    projectName: "Shirdi Plaza Retail Block",
    deletedBy: "Pratibha Nair",
    deletedAt: "2026-08-14T18:30:00+05:30",
    sizeBytes: 612 * kb,
  },
];

export const documentPages: Record<string, DocumentPage[]> = {
  "f-1": [
    {
      page: 1,
      heading: "STR-104 — Podium Slab Reinforcement Detail (R03)",
      body: [
        "Project: Aaditya Residency, Ghatkopar West, Mumbai",
        "Consultant: R D Consultants, Mumbai",
        "Issued for construction on 26 September 2026. Supersedes revision R02 dated 30 August 2026.",
        "Concrete grade M30. Reinforcement Fe500D conforming to IS 1786.",
      ],
    },
    {
      page: 2,
      heading: "General Notes",
      body: [
        "1. All dimensions are in millimetres unless noted otherwise.",
        "2. Clear cover to slab reinforcement: 25 mm bottom, 20 mm top.",
        "3. Lap lengths as per IS 456 — minimum 50d for tension laps.",
        "4. Do not scale the drawing. Refer to architectural drawing A-204 for openings.",
      ],
    },
    {
      page: 3,
      heading: "Slab Panel Schedule",
      body: [
        "Panel P1: 12 mm dia at 150 mm c/c both ways, bottom.",
        "Panel P2: 12 mm dia at 125 mm c/c short span, 10 mm at 150 mm c/c long span.",
        "Panel P3: 16 mm dia at 150 mm c/c bottom, additional top steel at supports.",
      ],
    },
    {
      page: 4,
      heading: "Revision History",
      body: [
        "R03 — 26 Sep 2026: Additional top reinforcement at grid C/4 following the September review.",
        "R02 — 30 Aug 2026: Panel P2 spacing revised from 150 mm to 125 mm.",
        "R01 — 14 Jul 2026: First issue for construction.",
      ],
    },
  ],
};
