/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as FilesRouteImport } from './routes/files'
import { Route as HelpRouteImport } from './routes/help'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MRouteRouteImport } from './routes/m/route'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TrashRouteImport } from './routes/trash'
import { Route as MIndexRouteImport } from './routes/m/index'
import { Route as MActivityRouteImport } from './routes/m/activity'
import { Route as MCaptureRouteImport } from './routes/m/capture'
import { Route as MFilesRouteImport } from './routes/m/files'
import { Route as MHelpRouteImport } from './routes/m/help'
import { Route as MLoginRouteImport } from './routes/m/login'
import { Route as MMoreRouteImport } from './routes/m/more'
import { Route as MPhotosRouteImport } from './routes/m/photos'
import { Route as MSearchRouteImport } from './routes/m/search'
import { Route as MSettingsRouteImport } from './routes/m/settings'
import { Route as MTeamRouteImport } from './routes/m/team'
import { Route as MTrashRouteImport } from './routes/m/trash'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsProjectIdRouteRouteImport } from './routes/projects/$projectId/route'
import { Route as MFileFileIdRouteImport } from './routes/m/file/$fileId'
import { Route as MProjectsIndexRouteImport } from './routes/m/projects/index'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects/$projectId/index'
import { Route as ProjectsProjectIdActivityRouteImport } from './routes/projects/$projectId/activity'
import { Route as ProjectsProjectIdDocumentsRouteImport } from './routes/projects/$projectId/documents'
import { Route as ProjectsProjectIdDrawingsRouteImport } from './routes/projects/$projectId/drawings'
import { Route as ProjectsProjectIdPhotosRouteImport } from './routes/projects/$projectId/photos'
import { Route as ProjectsProjectIdTeamRouteImport } from './routes/projects/$projectId/team'
import { Route as MProjectsProjectIdIndexRouteImport } from './routes/m/projects/$projectId/index'
import { Route as MProjectsProjectIdAskRouteImport } from './routes/m/projects/$projectId/ask'
import { Route as MProjectsProjectIdDrawingsRouteImport } from './routes/m/projects/$projectId/drawings'
import { Route as MProjectsProjectIdPhotosRouteImport } from './routes/m/projects/$projectId/photos'
import { Route as MProjectsProjectIdDocumentsIndexRouteImport } from './routes/m/projects/$projectId/documents/index'
import { Route as MProjectsProjectIdDocumentsFolderIdRouteImport } from './routes/m/projects/$projectId/documents/$folderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MRouteRoute = MRouteRouteImport.update({
  id: '/m',
  path: '/m',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TrashRoute = TrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => rootRouteImport,
} as any)
const MIndexRoute = MIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MRouteRoute,
} as any)
const MActivityRoute = MActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => MRouteRoute,
} as any)
const MCaptureRoute = MCaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => MRouteRoute,
} as any)
const MFilesRoute = MFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => MRouteRoute,
} as any)
const MHelpRoute = MHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => MRouteRoute,
} as any)
const MLoginRoute = MLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => MRouteRoute,
} as any)
const MMoreRoute = MMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => MRouteRoute,
} as any)
const MPhotosRoute = MPhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => MRouteRoute,
} as any)
const MSearchRoute = MSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => MRouteRoute,
} as any)
const MSettingsRoute = MSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MRouteRoute,
} as any)
const MTeamRoute = MTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => MRouteRoute,
} as any)
const MTrashRoute = MTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => MRouteRoute,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRouteRoute = ProjectsProjectIdRouteRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const MFileFileIdRoute = MFileFileIdRouteImport.update({
  id: '/file/$fileId',
  path: '/file/$fileId',
  getParentRoute: () => MRouteRoute,
} as any)
const MProjectsIndexRoute = MProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => MRouteRoute,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectIdRouteRoute,
} as any)
const ProjectsProjectIdActivityRoute =
  ProjectsProjectIdActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)
const ProjectsProjectIdDocumentsRoute =
  ProjectsProjectIdDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)
const ProjectsProjectIdDrawingsRoute =
  ProjectsProjectIdDrawingsRouteImport.update({
    id: '/drawings',
    path: '/drawings',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)
const ProjectsProjectIdPhotosRoute = ProjectsProjectIdPhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => ProjectsProjectIdRouteRoute,
} as any)
const ProjectsProjectIdTeamRoute = ProjectsProjectIdTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => ProjectsProjectIdRouteRoute,
} as any)
const MProjectsProjectIdIndexRoute = MProjectsProjectIdIndexRouteImport.update({
  id: '/projects/$projectId/',
  path: '/projects/$projectId/',
  getParentRoute: () => MRouteRoute,
} as any)
const MProjectsProjectIdAskRoute = MProjectsProjectIdAskRouteImport.update({
  id: '/projects/$projectId/ask',
  path: '/projects/$projectId/ask',
  getParentRoute: () => MRouteRoute,
} as any)
const MProjectsProjectIdDrawingsRoute =
  MProjectsProjectIdDrawingsRouteImport.update({
    id: '/projects/$projectId/drawings',
    path: '/projects/$projectId/drawings',
    getParentRoute: () => MRouteRoute,
  } as any)
const MProjectsProjectIdPhotosRoute =
  MProjectsProjectIdPhotosRouteImport.update({
    id: '/projects/$projectId/photos',
    path: '/projects/$projectId/photos',
    getParentRoute: () => MRouteRoute,
  } as any)
const MProjectsProjectIdDocumentsIndexRoute =
  MProjectsProjectIdDocumentsIndexRouteImport.update({
    id: '/projects/$projectId/documents/',
    path: '/projects/$projectId/documents/',
    getParentRoute: () => MRouteRoute,
  } as any)
const MProjectsProjectIdDocumentsFolderIdRoute =
  MProjectsProjectIdDocumentsFolderIdRouteImport.update({
    id: '/projects/$projectId/documents/$folderId',
    path: '/projects/$projectId/documents/$folderId',
    getParentRoute: () => MRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/m': typeof MRouteRouteWithChildren
  '/activity': typeof ActivityRoute
  '/ai': typeof AiRoute
  '/assistant': typeof AssistantRoute
  '/files': typeof FilesRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/trash': typeof TrashRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteRouteWithChildren
  '/m/activity': typeof MActivityRoute
  '/m/capture': typeof MCaptureRoute
  '/m/files': typeof MFilesRoute
  '/m/help': typeof MHelpRoute
  '/m/login': typeof MLoginRoute
  '/m/more': typeof MMoreRoute
  '/m/photos': typeof MPhotosRoute
  '/m/search': typeof MSearchRoute
  '/m/settings': typeof MSettingsRoute
  '/m/team': typeof MTeamRoute
  '/m/trash': typeof MTrashRoute
  '/m/': typeof MIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/m/file/$fileId': typeof MFileFileIdRoute
  '/projects/$projectId/activity': typeof ProjectsProjectIdActivityRoute
  '/projects/$projectId/documents': typeof ProjectsProjectIdDocumentsRoute
  '/projects/$projectId/drawings': typeof ProjectsProjectIdDrawingsRoute
  '/projects/$projectId/photos': typeof ProjectsProjectIdPhotosRoute
  '/projects/$projectId/team': typeof ProjectsProjectIdTeamRoute
  '/m/projects/': typeof MProjectsIndexRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/m/projects/$projectId/ask': typeof MProjectsProjectIdAskRoute
  '/m/projects/$projectId/drawings': typeof MProjectsProjectIdDrawingsRoute
  '/m/projects/$projectId/photos': typeof MProjectsProjectIdPhotosRoute
  '/m/projects/$projectId/': typeof MProjectsProjectIdIndexRoute
  '/m/projects/$projectId/documents/$folderId': typeof MProjectsProjectIdDocumentsFolderIdRoute
  '/m/projects/$projectId/documents/': typeof MProjectsProjectIdDocumentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/ai': typeof AiRoute
  '/assistant': typeof AssistantRoute
  '/files': typeof FilesRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/trash': typeof TrashRoute
  '/m/activity': typeof MActivityRoute
  '/m/capture': typeof MCaptureRoute
  '/m/files': typeof MFilesRoute
  '/m/help': typeof MHelpRoute
  '/m/login': typeof MLoginRoute
  '/m/more': typeof MMoreRoute
  '/m/photos': typeof MPhotosRoute
  '/m/search': typeof MSearchRoute
  '/m/settings': typeof MSettingsRoute
  '/m/team': typeof MTeamRoute
  '/m/trash': typeof MTrashRoute
  '/m': typeof MIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/m/file/$fileId': typeof MFileFileIdRoute
  '/projects/$projectId/activity': typeof ProjectsProjectIdActivityRoute
  '/projects/$projectId/documents': typeof ProjectsProjectIdDocumentsRoute
  '/projects/$projectId/drawings': typeof ProjectsProjectIdDrawingsRoute
  '/projects/$projectId/photos': typeof ProjectsProjectIdPhotosRoute
  '/projects/$projectId/team': typeof ProjectsProjectIdTeamRoute
  '/m/projects': typeof MProjectsIndexRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/m/projects/$projectId/ask': typeof MProjectsProjectIdAskRoute
  '/m/projects/$projectId/drawings': typeof MProjectsProjectIdDrawingsRoute
  '/m/projects/$projectId/photos': typeof MProjectsProjectIdPhotosRoute
  '/m/projects/$projectId': typeof MProjectsProjectIdIndexRoute
  '/m/projects/$projectId/documents/$folderId': typeof MProjectsProjectIdDocumentsFolderIdRoute
  '/m/projects/$projectId/documents': typeof MProjectsProjectIdDocumentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/m': typeof MRouteRouteWithChildren
  '/activity': typeof ActivityRoute
  '/ai': typeof AiRoute
  '/assistant': typeof AssistantRoute
  '/files': typeof FilesRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/trash': typeof TrashRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteRouteWithChildren
  '/m/activity': typeof MActivityRoute
  '/m/capture': typeof MCaptureRoute
  '/m/files': typeof MFilesRoute
  '/m/help': typeof MHelpRoute
  '/m/login': typeof MLoginRoute
  '/m/more': typeof MMoreRoute
  '/m/photos': typeof MPhotosRoute
  '/m/search': typeof MSearchRoute
  '/m/settings': typeof MSettingsRoute
  '/m/team': typeof MTeamRoute
  '/m/trash': typeof MTrashRoute
  '/m/': typeof MIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/m/file/$fileId': typeof MFileFileIdRoute
  '/projects/$projectId/activity': typeof ProjectsProjectIdActivityRoute
  '/projects/$projectId/documents': typeof ProjectsProjectIdDocumentsRoute
  '/projects/$projectId/drawings': typeof ProjectsProjectIdDrawingsRoute
  '/projects/$projectId/photos': typeof ProjectsProjectIdPhotosRoute
  '/projects/$projectId/team': typeof ProjectsProjectIdTeamRoute
  '/m/projects/': typeof MProjectsIndexRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/m/projects/$projectId/ask': typeof MProjectsProjectIdAskRoute
  '/m/projects/$projectId/drawings': typeof MProjectsProjectIdDrawingsRoute
  '/m/projects/$projectId/photos': typeof MProjectsProjectIdPhotosRoute
  '/m/projects/$projectId/': typeof MProjectsProjectIdIndexRoute
  '/m/projects/$projectId/documents/$folderId': typeof MProjectsProjectIdDocumentsFolderIdRoute
  '/m/projects/$projectId/documents/': typeof MProjectsProjectIdDocumentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/m'
    | '/activity'
    | '/ai'
    | '/assistant'
    | '/files'
    | '/help'
    | '/login'
    | '/search'
    | '/settings'
    | '/team'
    | '/trash'
    | '/projects/$projectId'
    | '/m/activity'
    | '/m/capture'
    | '/m/files'
    | '/m/help'
    | '/m/login'
    | '/m/more'
    | '/m/photos'
    | '/m/search'
    | '/m/settings'
    | '/m/team'
    | '/m/trash'
    | '/m/'
    | '/projects/'
    | '/m/file/$fileId'
    | '/projects/$projectId/activity'
    | '/projects/$projectId/documents'
    | '/projects/$projectId/drawings'
    | '/projects/$projectId/photos'
    | '/projects/$projectId/team'
    | '/m/projects/'
    | '/projects/$projectId/'
    | '/m/projects/$projectId/ask'
    | '/m/projects/$projectId/drawings'
    | '/m/projects/$projectId/photos'
    | '/m/projects/$projectId/'
    | '/m/projects/$projectId/documents/$folderId'
    | '/m/projects/$projectId/documents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/ai'
    | '/assistant'
    | '/files'
    | '/help'
    | '/login'
    | '/search'
    | '/settings'
    | '/team'
    | '/trash'
    | '/m/activity'
    | '/m/capture'
    | '/m/files'
    | '/m/help'
    | '/m/login'
    | '/m/more'
    | '/m/photos'
    | '/m/search'
    | '/m/settings'
    | '/m/team'
    | '/m/trash'
    | '/m'
    | '/projects'
    | '/m/file/$fileId'
    | '/projects/$projectId/activity'
    | '/projects/$projectId/documents'
    | '/projects/$projectId/drawings'
    | '/projects/$projectId/photos'
    | '/projects/$projectId/team'
    | '/m/projects'
    | '/projects/$projectId'
    | '/m/projects/$projectId/ask'
    | '/m/projects/$projectId/drawings'
    | '/m/projects/$projectId/photos'
    | '/m/projects/$projectId'
    | '/m/projects/$projectId/documents/$folderId'
    | '/m/projects/$projectId/documents'
  id:
    | '__root__'
    | '/'
    | '/m'
    | '/activity'
    | '/ai'
    | '/assistant'
    | '/files'
    | '/help'
    | '/login'
    | '/search'
    | '/settings'
    | '/team'
    | '/trash'
    | '/projects/$projectId'
    | '/m/activity'
    | '/m/capture'
    | '/m/files'
    | '/m/help'
    | '/m/login'
    | '/m/more'
    | '/m/photos'
    | '/m/search'
    | '/m/settings'
    | '/m/team'
    | '/m/trash'
    | '/m/'
    | '/projects/'
    | '/m/file/$fileId'
    | '/projects/$projectId/activity'
    | '/projects/$projectId/documents'
    | '/projects/$projectId/drawings'
    | '/projects/$projectId/photos'
    | '/projects/$projectId/team'
    | '/m/projects/'
    | '/projects/$projectId/'
    | '/m/projects/$projectId/ask'
    | '/m/projects/$projectId/drawings'
    | '/m/projects/$projectId/photos'
    | '/m/projects/$projectId/'
    | '/m/projects/$projectId/documents/$folderId'
    | '/m/projects/$projectId/documents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MRouteRoute: typeof MRouteRouteWithChildren
  ActivityRoute: typeof ActivityRoute
  AiRoute: typeof AiRoute
  AssistantRoute: typeof AssistantRoute
  FilesRoute: typeof FilesRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  TeamRoute: typeof TeamRoute
  TrashRoute: typeof TrashRoute
  ProjectsProjectIdRouteRoute: typeof ProjectsProjectIdRouteRouteWithChildren
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m': {
      id: '/m'
      path: '/m'
      fullPath: '/m'
      preLoaderRoute: typeof MRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trash': {
      id: '/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof TrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/': {
      id: '/m/'
      path: '/'
      fullPath: '/m/'
      preLoaderRoute: typeof MIndexRouteImport
      parentRoute: typeof MRouteRoute
    }
    '/m/activity': {
      id: '/m/activity'
      path: '/activity'
      fullPath: '/m/activity'
      preLoaderRoute: typeof MActivityRouteImport
      parentRoute: typeof MRouteRoute
    }
    '/m/capture': {
      id: '/m/capture'
      path: '/capture'
      fullPath: '/m/capture'
      preLoaderRoute: typeof MCaptureRouteImport
      parentRoute: typeof MRouteRoute
    }
    '/m/files': {
      id: '/m/files'
      path: '/files'
      fullPath: '/m/files'
      preLoaderRoute: typeof MFilesRouteImport
      parentRoute: typeof MRouteRoute
    }
    '/m/help': {
      id: '/m/help'
      path: '/help'
      fullPath: '/m/help'
      preLoaderRoute: typeof MHelpRouteImport
      parentRoute: typeof MRouteRoute
    }
    '/m/login': {
      id: '/m/login'
      path: '/login'
      fullPath: '/m/login'
      preLoaderRoute: typeof MLoginRouteImport
      parentRoute: typeof MRouteRoute
    }
    '/m/more': {
      id: '/m/more'
      path: '/more'
      fullPath: '/m/more'
      preLoaderRoute: typeof MMoreRouteImport
      parentRoute: typeof MRouteRoute
    }
    '/m/photos': {
      id: '/m/photos'
      path: '/photos'
      fullPath: '/m/photos'
      preLoaderRoute: typeof MPhotosRouteImport
      parentRoute: typeof MRouteRoute
    }
    '/m/search': {
      id: '/m/search'
      path: '/search'
      fullPath: '/m/search'
      preLoaderRoute: typeof MSearchRouteImport
      parentRoute: typeof MRouteRoute
    }
    '/m/settings': {
      id: '/m/settings'
      path: '/settings'
      fullPath: '/m/settings'
      preLoaderRoute: typeof MSettingsRouteImport
      parentRoute: typeof MRouteRoute
    }
    '/m/team': {
      id: '/m/team'
      path: '/team'
      fullPath: '/m/team'
      preLoaderRoute: typeof MTeamRouteImport
      parentRoute: typeof MRouteRoute
    }
    '/m/trash': {
      id: '/m/trash'
      path: '/trash'
      fullPath: '/m/trash'
      preLoaderRoute: typeof MTrashRouteImport
      parentRoute: typeof MRouteRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/file/$fileId': {
      id: '/m/file/$fileId'
      path: '/file/$fileId'
      fullPath: '/m/file/$fileId'
      preLoaderRoute: typeof MFileFileIdRouteImport
      parentRoute: typeof MRouteRoute
    }
    '/m/projects/': {
      id: '/m/projects/'
      path: '/projects'
      fullPath: '/m/projects/'
      preLoaderRoute: typeof MProjectsIndexRouteImport
      parentRoute: typeof MRouteRoute
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/activity': {
      id: '/projects/$projectId/activity'
      path: '/activity'
      fullPath: '/projects/$projectId/activity'
      preLoaderRoute: typeof ProjectsProjectIdActivityRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/documents': {
      id: '/projects/$projectId/documents'
      path: '/documents'
      fullPath: '/projects/$projectId/documents'
      preLoaderRoute: typeof ProjectsProjectIdDocumentsRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/drawings': {
      id: '/projects/$projectId/drawings'
      path: '/drawings'
      fullPath: '/projects/$projectId/drawings'
      preLoaderRoute: typeof ProjectsProjectIdDrawingsRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/photos': {
      id: '/projects/$projectId/photos'
      path: '/photos'
      fullPath: '/projects/$projectId/photos'
      preLoaderRoute: typeof ProjectsProjectIdPhotosRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/projects/$projectId/team': {
      id: '/projects/$projectId/team'
      path: '/team'
      fullPath: '/projects/$projectId/team'
      preLoaderRoute: typeof ProjectsProjectIdTeamRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/m/projects/$projectId/': {
      id: '/m/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/m/projects/$projectId/'
      preLoaderRoute: typeof MProjectsProjectIdIndexRouteImport
      parentRoute: typeof MRouteRoute
    }
    '/m/projects/$projectId/ask': {
      id: '/m/projects/$projectId/ask'
      path: '/projects/$projectId/ask'
      fullPath: '/m/projects/$projectId/ask'
      preLoaderRoute: typeof MProjectsProjectIdAskRouteImport
      parentRoute: typeof MRouteRoute
    }
    '/m/projects/$projectId/drawings': {
      id: '/m/projects/$projectId/drawings'
      path: '/projects/$projectId/drawings'
      fullPath: '/m/projects/$projectId/drawings'
      preLoaderRoute: typeof MProjectsProjectIdDrawingsRouteImport
      parentRoute: typeof MRouteRoute
    }
    '/m/projects/$projectId/photos': {
      id: '/m/projects/$projectId/photos'
      path: '/projects/$projectId/photos'
      fullPath: '/m/projects/$projectId/photos'
      preLoaderRoute: typeof MProjectsProjectIdPhotosRouteImport
      parentRoute: typeof MRouteRoute
    }
    '/m/projects/$projectId/documents/': {
      id: '/m/projects/$projectId/documents/'
      path: '/projects/$projectId/documents'
      fullPath: '/m/projects/$projectId/documents/'
      preLoaderRoute: typeof MProjectsProjectIdDocumentsIndexRouteImport
      parentRoute: typeof MRouteRoute
    }
    '/m/projects/$projectId/documents/$folderId': {
      id: '/m/projects/$projectId/documents/$folderId'
      path: '/projects/$projectId/documents/$folderId'
      fullPath: '/m/projects/$projectId/documents/$folderId'
      preLoaderRoute: typeof MProjectsProjectIdDocumentsFolderIdRouteImport
      parentRoute: typeof MRouteRoute
    }
  }
}

interface MRouteRouteChildren {
  MActivityRoute: typeof MActivityRoute
  MCaptureRoute: typeof MCaptureRoute
  MFilesRoute: typeof MFilesRoute
  MHelpRoute: typeof MHelpRoute
  MLoginRoute: typeof MLoginRoute
  MMoreRoute: typeof MMoreRoute
  MPhotosRoute: typeof MPhotosRoute
  MSearchRoute: typeof MSearchRoute
  MSettingsRoute: typeof MSettingsRoute
  MTeamRoute: typeof MTeamRoute
  MTrashRoute: typeof MTrashRoute
  MIndexRoute: typeof MIndexRoute
  MFileFileIdRoute: typeof MFileFileIdRoute
  MProjectsIndexRoute: typeof MProjectsIndexRoute
  MProjectsProjectIdAskRoute: typeof MProjectsProjectIdAskRoute
  MProjectsProjectIdDrawingsRoute: typeof MProjectsProjectIdDrawingsRoute
  MProjectsProjectIdPhotosRoute: typeof MProjectsProjectIdPhotosRoute
  MProjectsProjectIdIndexRoute: typeof MProjectsProjectIdIndexRoute
  MProjectsProjectIdDocumentsFolderIdRoute: typeof MProjectsProjectIdDocumentsFolderIdRoute
  MProjectsProjectIdDocumentsIndexRoute: typeof MProjectsProjectIdDocumentsIndexRoute
}

const MRouteRouteChildren: MRouteRouteChildren = {
  MActivityRoute: MActivityRoute,
  MCaptureRoute: MCaptureRoute,
  MFilesRoute: MFilesRoute,
  MHelpRoute: MHelpRoute,
  MLoginRoute: MLoginRoute,
  MMoreRoute: MMoreRoute,
  MPhotosRoute: MPhotosRoute,
  MSearchRoute: MSearchRoute,
  MSettingsRoute: MSettingsRoute,
  MTeamRoute: MTeamRoute,
  MTrashRoute: MTrashRoute,
  MIndexRoute: MIndexRoute,
  MFileFileIdRoute: MFileFileIdRoute,
  MProjectsIndexRoute: MProjectsIndexRoute,
  MProjectsProjectIdAskRoute: MProjectsProjectIdAskRoute,
  MProjectsProjectIdDrawingsRoute: MProjectsProjectIdDrawingsRoute,
  MProjectsProjectIdPhotosRoute: MProjectsProjectIdPhotosRoute,
  MProjectsProjectIdIndexRoute: MProjectsProjectIdIndexRoute,
  MProjectsProjectIdDocumentsFolderIdRoute:
    MProjectsProjectIdDocumentsFolderIdRoute,
  MProjectsProjectIdDocumentsIndexRoute: MProjectsProjectIdDocumentsIndexRoute,
}

const MRouteRouteWithChildren =
  MRouteRoute._addFileChildren(MRouteRouteChildren)

interface ProjectsProjectIdRouteRouteChildren {
  ProjectsProjectIdActivityRoute: typeof ProjectsProjectIdActivityRoute
  ProjectsProjectIdDocumentsRoute: typeof ProjectsProjectIdDocumentsRoute
  ProjectsProjectIdDrawingsRoute: typeof ProjectsProjectIdDrawingsRoute
  ProjectsProjectIdPhotosRoute: typeof ProjectsProjectIdPhotosRoute
  ProjectsProjectIdTeamRoute: typeof ProjectsProjectIdTeamRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
}

const ProjectsProjectIdRouteRouteChildren: ProjectsProjectIdRouteRouteChildren =
  {
    ProjectsProjectIdActivityRoute: ProjectsProjectIdActivityRoute,
    ProjectsProjectIdDocumentsRoute: ProjectsProjectIdDocumentsRoute,
    ProjectsProjectIdDrawingsRoute: ProjectsProjectIdDrawingsRoute,
    ProjectsProjectIdPhotosRoute: ProjectsProjectIdPhotosRoute,
    ProjectsProjectIdTeamRoute: ProjectsProjectIdTeamRoute,
    ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
  }

const ProjectsProjectIdRouteRouteWithChildren =
  ProjectsProjectIdRouteRoute._addFileChildren(
    ProjectsProjectIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MRouteRoute: MRouteRouteWithChildren,
  ActivityRoute: ActivityRoute,
  AiRoute: AiRoute,
  AssistantRoute: AssistantRoute,
  FilesRoute: FilesRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  TeamRoute: TeamRoute,
  TrashRoute: TrashRoute,
  ProjectsProjectIdRouteRoute: ProjectsProjectIdRouteRouteWithChildren,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
